export const a = [
  {
    category: "產品包裝承製",
    company: "德商",
    description: "AARON",
    explanation: "",
    image_format: "png",
    path: "home-ex/package_aaron.png",
    first: "產品包裝承製｜德商",
    second: "AARON",
  },
  {
    category: "產品包裝承製",
    company: "德商",
    description: "NEXTCOVER",
    explanation: "",
    image_format: "png",
    path: "home-ex/package_nextcover.png",
    first: "產品包裝承製｜德商",
    second: "NEXTCOVER",
  },
  {
    category: "精裝書冊承製",
    company: "彰化縣明倫國中美術班",
    description: "",
    explanation: "",
    image_format: "png",
    path: "home-ex/book_minglun.png",
    first: "精裝書冊承製",
    second: "彰化縣明倫國中美術班",
  },
  {
    category: "客製專貼",
    company: "",
    description: "",
    explanation: "",
    image_format: "JPG",
    path: "home-ex/custom_sticker.jpg",
    first: "",
    second: "客製專貼",
  },
  {
    category: "口碑行銷",
    company: "",
    description: "十方光合",
    explanation: "",
    image_format: "png",
    path: "home-ex/marketing_sunlight.png",
    first: "口碑行銷",
    second: "十方光合",
  },
  {
    category: "口碑行銷",
    company: "",
    description: "EatFun",
    explanation: "",
    image_format: "png",
    path: "home-ex/marketing_eatfun.png",
    first: "口碑行銷",
    second: "EatFun",
  },
  {
    category: "口碑行銷",
    company: "",
    description: "HighKart微型電動車",
    explanation: "",
    image_format: "png",
    path: "home-ex/marketing_highkart.png",
    first: "口碑行銷",
    second: "HighKart微型電動車",
  },
  {
    category: "品牌規劃",
    company: "華威綠能科技有限公司",
    description: "VI視覺識別規劃、識別應用設計",
    explanation: "",
    image_format: "JPG",
    path: "home-ex/branding_huawei_green.jpg",
    first: "品牌規劃｜VI視覺識別規劃｜識別應用設計",
    second: "華威綠能科技有限公司",
  },
  {
    category: "品牌規劃",
    company: "上海鴻·美術館",
    description: "VI視覺識別規劃、識別應用設計",
    explanation: "",
    image_format: "JPG",
    path: "home-ex/branding_shanghai_hong.jpg",
    first: "品牌規劃｜VI視覺識別規劃｜識別應用設計",
    second: "上海鴻·美術館",
  },
  {
    category: "品牌規劃",
    company: "",
    description: "VI視覺識別規劃、識別應用設計、印刷品設計",
    explanation: "捷風車業",
    image_format: "png",
    path: "home-ex/branding_jiefeng_motor.png",
    first: "品牌規劃｜VI視覺識別規劃｜識別應用設計｜印刷品設計",
    second: "捷風車業",
  },
  {
    category: "平面設計",
    company: "",
    description: "印刷品設計",
    explanation: "藝時代",
    image_format: "png",
    path: "home-ex/design_art_era.png",
    first: "平面設計｜印刷品設計",
    second: "藝時代",
  },
  {
    category: "平面設計",
    company: "",
    description: "印刷品設計",
    explanation: "BRASS HANA",
    image_format: "png",
    path: "home-ex/design_brass_hana.png",
    first: "平面設計｜印刷品設計",
    second: "BRASS HANA",
  },
  {
    category: "平面設計",
    company: "彰化縣政府",
    description: "青年創業一對一陪伴輔導服務",
    explanation: "",
    image_format: "png",
    path: "home-ex/design_changhua_gov.png",
    first: "平面設計",
    second: "彰化縣政府青年創業一對一陪伴輔導服務",
  },
  {
    category: "網站設計",
    company: "安禾建設",
    description: "",
    explanation: "",
    image_format: "png",
    path: "home-ex/web_anhe_construction.png",
    first: "網站設計",
    second: "安禾建設",
  },
  {
    category: "網站設計",
    company: "安閔",
    description: "AHXYC",
    explanation: "",
    image_format: "png",
    path: "home-ex/web_ahxyc.png",
    first: "網站設計",
    second: "安閔AHXYC",
  },
  {
    category: "行銷策略規劃",
    company: "漢英建設",
    description: "社群行銷、廣告投放",
    explanation: "",
    image_format: "png",
    path: "home-ex/strategy_hanying_construction.png",
    first: "行銷策略規劃｜社群行銷｜廣告投放",
    second: "漢英建設",
  },
  {
    category: "行銷策略規劃",
    company: "業通高空室",
    description: "社群行銷、廣告投放",
    explanation: "",
    image_format: "png",
    path: "home-ex/strategy_yetong_skywalker.png",
    first: "行銷策略規劃｜社群行銷｜廣告投放",
    second: "業通高空室",
  },
  {
    category: "行銷策略規劃",
    company: "中橙隔熱紙",
    description: "社群行銷、廣告投放",
    explanation: "",
    image_format: "png",
    path: "home-ex/strategy_zhongcheng_tint.png",
    first: "行銷策略規劃｜社群行銷｜廣告投放",
    second: "中橙隔熱紙",
  },
  {
    category: "印刷物承製",
    company: "彰化。旅庫",
    description: "",
    explanation: "",
    image_format: "JPG",
    path: "home-ex/print_travel_library.jpg",
    first: "印刷物承製",
    second: "彰化。旅庫",
  },
  {
    category: "LINE官方帳號",
    company: "益載室內裝修有限公司",
    description: "",
    explanation: "",
    image_format: "png",
    path: "home-ex/line_yizai_decoration.png",
    first: "LINE官方帳號",
    second: "益載室內裝修有限公司",
  },
];
