export const a = {
  a: [
    {
      category: "產品包裝承製",
      company: "德商",
      description: "AARON",
      image_format: "png",
      path: "a/package_aaron.png",
      first: "產品包裝承製｜德商",
      second: "AARON",
    },
    {
      category: "產品包裝承製",
      company: "德商",
      description: "BLUECHAIN",
      image_format: "png",
      path: "a/package_bluechain.png",
      first: "產品包裝承製｜德商",
      second: "BLUECHAIN",
    },
    {
      category: "產品包裝承製",
      company: "德商",
      description: "NEXTCOVER",
      image_format: "png",
      path: "a/package_nextcover.png",
      first: "產品包裝承製｜德商",
      second: "NEXTCOVER",
    },
    {
      category: "產品包裝承製",
      company: "",
      description: "啾啾咖啡",
      image_format: "png",
      path: "a/package_jojocoffee.png",
      first: "產品包裝承製",
      second: "啾啾咖啡",
    },
    {
      category: "產品包裝承製",
      company: "英商",
      description: "Halfords",
      image_format: "png",
      path: "a/package_halfords.png",
      first: "產品包裝承製｜英商",
      second: "Halfords",
    },
    {
      category: "產品包裝承製",
      company: "永濂有限公司",
      description: "",
      image_format: "png",
      path: "a/package_yonglian.png",
      first: "產品包裝承製",
      second: "永濂有限公司",
    },
    {
      category: "產品包裝承製",
      company: "",
      description: "SUPER B ",
      image_format: "png",
      path: "a/package_superb_space.png",
      first: "產品包裝承製",
      second: "SUPER B ",
    },
    {
      category: "產品包裝承製",
      company: "",
      description: "SUPER B",
      image_format: "png",
      path: "a/package_superb.png",
      first: "產品包裝承製",
      second: "SUPER B",
    },
    {
      category: "產品吊卡承製",
      company: "德商",
      description: "Fuxon",
      image_format: "png",
      path: "a/tag_fuxon.png",
      first: "產品吊卡承製｜德商",
      second: "Fuxon",
    },
    {
      category: "產品吊卡承製",
      company: "",
      description: "i冒號SY",
      image_format: "png",
      path: "a/tag_isy.png",
      first: "產品吊卡承製",
      second: "i冒號SY",
    },
    {
      category: "產品吊卡承製",
      company: "",
      description: "SATORI",
      image_format: "png",
      path: "a/tag_satori.png",
      first: "產品吊卡承製",
      second: "SATORI",
    },
    {
      category: "產品紙袋承製",
      company: "",
      description: "Body Soigne",
      image_format: "png",
      path: "a/bag_bodysoigne.png",
      first: "產品紙袋承製",
      second: "Body Soigne",
    },
    {
      category: "精裝書冊承製",
      company: "彰化縣和美鎮邉社社區發展協會",
      description: "",
      image_format: "png",
      path: "a/book_huanshe.png",
      first: "精裝書冊承製",
      second: "彰化縣和美鎮邉社社區發展協會",
    },
    {
      category: "精裝書冊承製",
      company: "彰化縣明倫國中美術班",
      description: "",
      image_format: "png",
      path: "a/book_minglun.png",
      first: "精裝書冊承製",
      second: "彰化縣明倫國中美術班",
    },
    {
      category: "客製喜帖",
      company: "",
      description: "",
      image_format: "JPG",
      path: "a/wedding_invitation.jpg",
      first: "",
      second: "客製喜帖",
    },
    {
      category: "印刷物承製",
      company: "彰化 | 旅庫",
      description: "",
      image_format: "JPG",
      path: "a/print_travel_library.jpg",
      first: "印刷物承製 | 彰化",
      second: "旅庫",
    },
  ],
  b: [
    {
      category: "口碑行銷",
      company: "",
      description: "十方光合",
      image_format: "png",
      path: "b/marketing_sunlight.png",
      first: "口碑行銷",
      second: "十方光合",
    },
    {
      category: "口碑行銷",
      company: "",
      description: "EatFun",
      image_format: "png",
      path: "b/marketing_eatfun.png",
      first: "口碑行銷",
      second: "EatFun",
    },
    {
      category: "口碑行銷",
      company: "",
      description: "HighKart微型電動車",
      image_format: "png",
      path: "b/marketing_highkart.png",
      first: "口碑行銷",
      second: "HighKart微型電動車",
    },
  ],
  c: [
    {
      category: "品牌規劃",
      company: "",
      description: "印刷品設計｜屋咪Woomi",
      image_format: "png",
      path: "c/branding_woomi.png",
      first: "品牌規劃｜印刷品設計",
      second: "屋咪Woomi",
    },
    {
      category: "品牌規劃",
      company: "",
      description: "LOGO標誌｜安達速運",
      image_format: "png",
      path: "c/branding_anda_express.png",
      first: "品牌規劃｜LOGO標誌",
      second: "安達速運",
    },
    {
      category: "品牌規劃",
      company: "",
      description: "LOGO標誌｜初旭民宿",
      image_format: "png",
      path: "c/branding_chuxu_homestay.png",
      first: "品牌規劃｜LOGO標誌",
      second: "初旭民宿",
    },
    {
      category: "品牌規劃",
      company: "",
      description:
        "VI視覺識別規劃｜識別應用設計｜包裝設計｜印刷品設計｜嘉義涼麵",
      image_format: "JPG",
      path: "c/branding_chiayi_cold_noodle.jpg",
      first: "品牌規劃｜VI視覺識別規劃｜識別應用設計｜包裝設計｜印刷品設計",
      second: "嘉義涼麵",
    },
    {
      category: "品牌規劃",
      company: "",
      description: "VI視覺識別規劃｜識別應用設計｜福曜開發",
      image_format: "png",
      path: "c/branding_fuyao_development.png",
      first: "品牌規劃｜VI視覺識別規劃｜識別應用設計",
      second: "福曜開發",
    },
    {
      category: "品牌規劃",
      company: "華威綠能科技有限公司",
      description: "VI視覺識別規劃｜識別應用設計",
      image_format: "JPG",
      path: "c/branding_huawei_green_energy.jpg",
      first: "品牌規劃｜VI視覺識別規劃｜識別應用設計",
      second: "華威綠能科技有限公司",
    },
    {
      category: "品牌規劃",
      company: "",
      description: "VI視覺識別規劃｜識別應用設計｜華友週報",
      image_format: "avif",
      path: "c/branding_huayou_weekly.avif",
      first: "品牌規劃｜VI視覺識別規劃｜識別應用設計",
      second: "華友週報",
    },
    {
      category: "品牌規劃",
      company: "上海鴻·美術館",
      description: "VI視覺識別規劃｜識別應用設計",
      image_format: "JPG",
      path: "c/branding_shanghai_hong.jpg",
      first: "品牌規劃｜VI視覺識別規劃｜識別應用設計",
      second: "上海鴻·美術館",
    },
    {
      category: "品牌規劃",
      company: "",
      description: "VI視覺識別規劃｜識別應用設計｜印刷品設計｜捷風車業",
      image_format: "png",
      path: "c/branding_jiefeng_motor.png",
      first: "品牌規劃｜VI視覺識別規劃｜識別應用設計｜印刷品設計",
      second: "捷風車業",
    },
    {
      category: "平面設計",
      company: "",
      description: "包裝規劃｜CHUANXI",
      image_format: "png",
      path: "c/design_chuanxi.png",
      first: "平面設計｜包裝規劃",
      second: "CHUANXI",
    },
    {
      category: "平面設計",
      company: "",
      description: "包裝規劃｜LoFreys",
      image_format: "png",
      path: "c/design_lofreys.png",
      first: "平面設計｜包裝規劃",
      second: "LoFreys",
    },
    {
      category: "平面設計",
      company: "",
      description: "印刷品設計｜藝時代",
      image_format: "png",
      path: "c/design_art_era.png",
      first: "平面設計｜印刷品設計",
      second: "藝時代",
    },
    {
      category: "平面設計",
      company: "",
      description: "印刷品設計｜BRASS HANA",
      image_format: "png",
      path: "c/design_brass_hana.png",
      first: "平面設計｜印刷品設計",
      second: "BRASS HANA",
    },
    {
      category: "平面設計",
      company: "彰化縣政府",
      description: "青年創業一對一陪伴輔導服務",
      image_format: "png",
      path: "c/design_changhua_gov.png",
      first: "平面設計",
      second: "彰化縣政府青年創業一對一陪伴輔導服務",
    },
  ],
  d: [
    {
      category: "社群行銷",
      company: "",
      description: "廣告投放｜現代牙醫診所",
      image_format: "png",
      path: "d/social_modern_dentist.png",
      first: "社群行銷｜廣告投放",
      second: "現代牙醫診所",
    },
    {
      category: "社群行銷",
      company: "",
      description: "謙浪屹飽_工作區域1",
      image_format: "png",
      path: "d/social_feed_strays.png",
      first: "社群行銷",
      second: "謙浪屹飽_工作區域1",
    },
    {
      category: "社群行銷",
      company: "",
      description: "影音製作｜PPTOY",
      image_format: "png",
      path: "d/social_pptoy.png",
      first: "社群行銷｜影音製作",
      second: "PPTOY",
    },
    {
      category: "行銷策略規劃",
      company: "",
      description: "社群行銷｜廣告投放｜漢英建設",
      image_format: "png",
      path: "d/strategy_hanying_construction.png",
      first: "行銷策略規劃｜社群行銷｜廣告投放",
      second: "漢英建設",
    },
    {
      category: "行銷策略規劃",
      company: "",
      description: "社群行銷｜廣告投放｜嘉點貼膜",
      image_format: "png",
      path: "d/strategy_jiadian_film.png",
      first: "行銷策略規劃｜社群行銷｜廣告投放",
      second: "嘉點貼膜",
    },
    {
      category: "行銷策略規劃",
      company: "",
      description: "社群行銷｜廣告投放｜晴簾坊窗簾傢飾",
      image_format: "png",
      path: "d/strategy_qinglianfang_curtain.png",
      first: "行銷策略規劃｜社群行銷｜廣告投放",
      second: "晴簾坊窗簾傢飾",
    },
    {
      category: "行銷策略規劃",
      company: "",
      description: "社群行銷｜廣告投放｜業通高空車",
      image_format: "png",
      path: "d/strategy_yetong_skywalker.png",
      first: "行銷策略規劃｜社群行銷｜廣告投放",
      second: "業通高空車",
    },
    {
      category: "行銷策略規劃",
      company: "",
      description: "社群行銷｜廣告投放｜中橙隔熱紙",
      image_format: "png",
      path: "d/strategy_zhongcheng_tint.png",
      first: "行銷策略規劃｜社群行銷｜廣告投放",
      second: "中橙隔熱紙",
    },
    {
      category: "行銷策略規劃",
      company: "",
      description: "社群行銷｜廣告投放｜中天精品典檔",
      image_format: "png",
      path: "d/strategy_zhongtian_pawnshop.png",
      first: "行銷策略規劃｜社群行銷｜廣告投放",
      second: "中天精品典檔",
    },
    {
      category: "行銷策略規劃",
      company: "",
      description: "社群行銷｜口碑行銷｜廣告投放｜威瑞生物科技",
      image_format: "png",
      path: "d/strategy_weirui_biotech.png",
      first: "行銷策略規劃｜社群行銷｜口碑行銷｜廣告投放",
      second: "威瑞生物科技",
    },
    {
      category: "行銷策略規劃",
      company: "",
      description: "社群行銷｜口碑行銷｜廣告投放｜EatFun",
      image_format: "png",
      path: "d/strategy_eatfun_marketing.png",
      first: "行銷策略規劃｜社群行銷｜口碑行銷｜廣告投放",
      second: "EatFun",
    },
    {
      category: "行銷策略規劃",
      company: "",
      description: "社群行銷｜口碑行銷｜廣告投放｜HighKart微型電動車",
      image_format: "png",
      path: "d/strategy_highkart_marketing.png",
      first: "行銷策略規劃｜社群行銷｜口碑行銷｜廣告投放",
      second: "HighKart微型電動車",
    },
    {
      category: "行銷策略規劃",
      company: "",
      description: "社群行銷｜影音製作｜HighKart微型電動車",
      image_format: "png",
      path: "d/strategy_highkart_video.png",
      first: "行銷策略規劃｜社群行銷｜影音製作",
      second: "HighKart微型電動車",
    },
    {
      category: "LINE官方帳號",
      company: "",
      description: "東之初",
      image_format: "png",
      path: "d/line_dongzhichu.png",
      first: "LINE官方帳號",
      second: "東之初",
    },
    {
      category: "LINE官方帳號",
      company: "益載室內裝修有限公司",
      description: "",
      image_format: "png",
      path: "d/line_yizai_decoration.png",
      first: "LINE官方帳號",
      second: "益載室內裝修有限公司",
    },
    {
      category: "LINE官方帳號",
      company: "",
      description: "中橙隔熱紙",
      image_format: "png",
      path: "d/line_zhongcheng_tint.png",
      first: "LINE官方帳號",
      second: "中橙隔熱紙",
    },
  ],
  e: [
    {
      category: "網站設計",
      company: "",
      description: "艾爾瑞特藝術所",
      image_format: "png",
      path: "e/web_art_lab.png",
      first: "網站設計",
      second: "艾爾瑞特藝術所",
    },
    {
      category: "網站設計",
      company: "安禾建設",
      description: "",
      image_format: "png",
      path: "e/web_anhe_construction.png",
      first: "網站設計",
      second: "安禾建設",
    },
    {
      category: "網站設計",
      company: "安閔",
      description: "AHXYC",
      image_format: "png",
      path: "e/web_ahxyc.png",
      first: "網站設計",
      second: "安閔AHXYC",
    },
    {
      category: "網站設計",
      company: "DBP得美袋製造股份有限公司",
      description: "",
      image_format: "png",
      path: "e/web_dbp_bag.png",
      first: "網站設計",
      second: "DBP得美袋製造股份有限公司",
    },
    {
      category: "網站設計",
      company: "",
      description: "MONGOLIAN安全帽",
      image_format: "png",
      path: "e/web_mongolian_helmet.png",
      first: "網站設計",
      second: "MONGOLIAN安全帽",
    },
  ],
};
