import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LeftNav } from "@/components/left-nav/left-nav";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <ConfigProvider
            theme={{
              components: {
                Form: {
                  labelColor: "white",
                },
                Input: {
                  paddingInline: 20,
                  paddingBlock: 12,
                  activeBorderColor: "transparent",
                  hoverBorderColor: "rgba(255, 255, 255, 0.3)",
                  activeShadow: "0 0 0 1px rgba(255, 255, 255, 0.3)",
                  colorTextPlaceholder: "rgba(255, 255, 255, 0.8)",
                },
                Radio: {
                  colorText: "rgba(255, 255, 255, 0.8)",
                  radioSize: 14,
                },
              },
              token: {
                colorTextPlaceholder: "rgba(255, 255, 255, 0.3)",
                borderRadius: 0, // ✅ 自定义 placeholder 颜色
                colorBgContainer: "black",
                colorBorder: "rgba(255, 255, 255, 0.3)",
              },
            }}
          >
            <div className="flex items-center w-screen h-screen">
              <LeftNav />
              <div className="flex-1">{children}</div>
            </div>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
