import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LeftNav } from "@/components/left-nav/left-nav";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AntdProvider } from "./antd-provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <AntdProvider>
            <div className="flex items-start w-screen h-screen">
              <LeftNav />
              <div className="flex-1">{children}</div>
            </div>
          </AntdProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
